services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis

    env_file:
      - .env
    volumes:
      - .:/app

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: [ "bash", "-c", "export PYTHONPATH=/app && ls && celery -A celery_config.app worker --pool solo --loglevel info" ]
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
